#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-4 -d I II III IV V VI VII VIII IX X
bspc monitor DP-2 -d I II III IV V VI VII VIII IX X

bspc config border_width 5
bspc config window_gap 12
bspc config split_ratio 12
bspc config pointer_follows_focus true
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config focused_border_color \#7231A7






bspc rule -a easyeffects monitor=DP-2 desktop=X
bspc rule -a Pavucontrol state=floating
bspc rule -a discord monitor=DP-2 desktop=I
bspc rule -a Steam monitor=DP-2 desktop=V
bspc rule -a Brave-browser-beta monitor=DP-2 desktop=II
bspc rule -a Lutris monitor=DP-2 desktop=IV

picom -b &
$HOME/.config/polybar/launch.sh &
nitrogen --restore &
/usr/bin/discord &
/usr/bin/shutter -silent & 
/usr/bin/brave-browser-beta &
/usr/games/steam -silent &
/usr/bin/alacritty &
/usr/games/lutris -silent &
/usr/bin/opentabletdriver -silent &
/usr/bin/easyeffects &
$HOME/.config/autostart/remapkeys.sh &
xsetroot -cursor_name left_ptr &

